### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by zimbatm** [pusher/pusher-logos#1]
@jpatel531 @stealthpig : people need to know in what conditions we release these assets.

**Comment by jpatel531** [comment]
I assume MIT?

**Comment by zimbatm** [comment]
For assets Creative Commons is generally more acceptable. I would probably just choose the version with no derivatives allowed: http://creativecommons.org/licenses/by-nd/4.0/

**Comment by alexpate** [comment]
@zimbatm Not sure whether a license is required, seems a bit overkill.

Saying that, have provided a bit more information to the readme (https://github.com/pusher/pusher-logos/commit/00fe56cb8c428d2c63359ba090d8fa09faeab4c0)

**Comment by zimbatm** [comment]
@alexpate it's necessary for legal if we want people to use our logos in their articles for example. It's better for us to describe clearly what we allow or not with the logos so we don't get bad surprises. I know it's boring stuff...

**Comment by alexpate** [comment]
@zimbatm To be honest, this is out of my remit :smile:

**Comment by zimbatm** [comment]
Yeah me too. /cc @ewmy

**Comment by ewmy** [comment]
It's definitely not standard to share brand assets with a CC license, and we are currently going through the process of getting our name and logos officially trademarked. We probably shouldn't pre-empt this process.

Let's close this for now and then maybe revisit when we are officially trademarked.

**Comment by zimbatm** [comment]
The issue is more about having a clear guideline for people who want to use our logos. Using CC is an implementation detail that I'm happy to drop.

I like what github has done for example: https://github.com/logos much less permissive but it covers most use cases.

**Comment by ewmy** [comment]
In that case, I think the guidelines we have on https://pusher.com/about/press already are sufficient for now. We can link the trademark text when we are trademarked as GitHub have done.
